[project]
# Site metadata
site_name = "AI2S Materials"
site_description = "Home for the University of Arizona AI2S teaching and workshop materials"
site_author = "AI2S Staff"
site_url = "ua-ai2s.github.io"
copyright = "Copyright &copy; 2019-2025 AI2S"

# Directories
site_dir = "site"

# Repository
repo_name = "ua-ai2s"
repo_url = "https://github.com/UA-AI2S/website-home"
edit_uri = "edit/main/docs/"

# Navigation
nav = [
  {"Home" = "index.md"}
]

# Theme configuration
[project.theme]
variant = "modern"
#custom_dir = "material/overrides"
language = "en"
favicon = "assets/ua.ico"
logo = "assets/ua.png"

# Theme features
features = [
  "navigation.instant",
  "navigation.tracking",
  "navigation.tabs",
  "navigation.tabs.sticky",
  "navigation.indexes",
  "navigation.top",
  "search.highlight",
  "search.share",
  "search.suggest"
]

# Font configuration
[project.theme.font]
text = "Montserrat"
code = "Regular"

# Color palette configuration
[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle = { icon = "material/brightness-auto", name = "Switch to light mode" }

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "home"
toggle = { icon = "material/brightness-7", name = "Switch to dark mode" }

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle = { icon = "material/brightness-4", name = "Switch to system preference" }

# Custom CSS and JavaScript
extra_css = ["stylesheets/extra.css"]

# Markdown extensions
markdown_extensions = [
  "abbr",
  "admonition",
  "attr_list",
  "def_list",
  "footnotes",
  "md_in_html",
  "tables",
  "pymdownx.caret",
  "pymdownx.details",
  "pymdownx.inlinehilite",
  "pymdownx.keys",
  "pymdownx.mark",
  "pymdownx.smartsymbols",
  "pymdownx.tilde"
]

[project.markdown_extensions.admonition]

[project.markdown_extensions.attr_list]

[project.markdown_extensions.md_in_html]

[project.markdown_extensions.tables]

[project.markdown_extensions.toc]
permalink = true

[project.markdown_extensions.pymdownx.details]

[project.markdown_extensions.pymdownx.arithmatex]
generic = true

[project.markdown_extensions.pymdownx.betterem]
smart_enable = "all"

[project.markdown_extensions.pymdownx.emoji]
emoji_index = "zensical.extensions.emoji.twemoji"
emoji_generator = "zensical.extensions.emoji.to_svg"

[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true

[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" }
]

[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
combine_header_slug = true

[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true